name: 'conversational_supply_chain'
version: '1.0.0'
config-version: 2

profile: 'conversational_supply_chain'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  conversational_supply_chain:

    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      +tags: ["intermediate"]

    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]

vars:
  start_date: '2016-01-01'
  end_date: '2018-12-31'

  late_delivery_threshold_days: 0
  critical_delay_threshold_days: 7

  high_value_order_threshold: 500

  positive_review_min_score: 4
  negative_review_max_score: 2
